---
# Variable configuration.
- include_tasks: variables.yml

- include_tasks: setup-Ubuntu.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml
- include_tasks: configure.yml
- include_tasks: restart.yml    

# Configure PostgreSQL.
- include_tasks: users.yml
- include_tasks: databases.yml
