version: '3.7'
services:  
  elasticsearch:
    # build:
    #   context: elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data/:rw
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - web
    container_name: elasticsearch  
  
  logstash:
    # build:
    #   context: logstash/
    image: docker.elastic.co/logstash/logstash-oss:6.6.0  
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "1025:1025/udp"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - web
    depends_on:
      - elasticsearch
    container_name: logstash  
  kibana:
    # build:
    #   context: kibana/
    image: docker.elastic.co/kibana/kibana-oss:6.6.0  
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - web
    depends_on:
      - elasticsearch
    container_name: kibana  
volumes:
  elasticsearch:
     driver: local
  
networks:
  web:
    external: true
